package engine.gl.vertex;

import org.lwjgl.opengl.GL44;

public enum DrawMode
{
    POINTS(GL44.GL_POINTS),
    LINE_STRIP(GL44.GL_LINE_STRIP),
    LINE_STRIP_ADJACENCY(GL44.GL_LINE_STRIP_ADJACENCY),
    LINE_LOOP(GL44.GL_LINE_LOOP),
    LINES(GL44.GL_LINES),
    LINES_ADJACENCY(GL44.GL_LINES_ADJACENCY),
    TRIANGLE_STRIP(GL44.GL_TRIANGLE_STRIP),
    TRIANGLE_STRIP_ADJACENCY(GL44.GL_TRIANGLE_STRIP_ADJACENCY),
    TRIANGLE_FAN(GL44.GL_TRIANGLE_FAN),
    TRIANGLES(GL44.GL_TRIANGLES),
    TRIANGLES_ADJACENCY(GL44.GL_TRIANGLES_ADJACENCY),
    QUADS(GL44.GL_QUADS),
    PATCHES(GL44.GL_PATCHES),
    ;
    
    public static final DrawMode DEFAULT = TRIANGLES;
    
    public final int ref;
    
    DrawMode(int ref)
    {
        this.ref = ref;
    }
}
